export type Partner = {
  name: string;
  slug: string;
  role?: string; // for featured partners only
  lead?: boolean; // marks the NBCUniversal "Founding" row
  years: number[];
  current?: boolean; // true if sponsoring 2026 (renders lime green on wall)
};

// Featured partners for the four-row "In Partnership With" block.
// Order matters: lead first, then the three siblings.
export const featuredPartners: Partner[] = [
  { name: "NBCUniversal", slug: "nbcuniversal", role: "Founding Partner", lead: true, years: [2023, 2024, 2025, 2026], current: true },
  { name: "Highbeam", slug: "highbeam", role: "Official Banking Partner", years: [2025, 2026], current: true },
  { name: "Flexport", slug: "flexport", role: "Official Logistics Partner", years: [2025, 2026], current: true },
  { name: "Richpanel", slug: "richpanel", role: "Official CX Partner", years: [2025, 2026], current: true },
];

// All partners, current and past, alphabetical by name.
// `current: true` = closed-won 2026 sponsor — renders in lime green on the wall.
export const allPartners: Partner[] = [
  { name: "Activate Talent", slug: "activate-talent", years: [2025, 2026], current: true },
  { name: "AfterSell", slug: "aftersell", years: [2024, 2025, 2026], current: true },
  { name: "Agentio", slug: "agentio", years: [2025] },
  { name: "Airwallex", slug: "airwallex", years: [2025] },
  { name: "Alby", slug: "alby", years: [2025] },
  { name: "AppLovin", slug: "applovin", years: [2025] },
  { name: "Aspire", slug: "aspire", years: [2024, 2025] },
  { name: "Barry's", slug: "barrys", years: [2025] },
  { name: "Bluecore", slug: "bluecore", years: [2025] },
  { name: "Channable", slug: "channable", years: [2025] },
  { name: "Chargeflow", slug: "chargeflow", years: [2025] },
  { name: "CrossFit", slug: "crossfit", years: [2025] },
  { name: "Doss", slug: "doss", years: [2025, 2026], current: true },
  { name: "DTConnect", slug: "dtconnect", years: [2025] },
  { name: "Eko", slug: "eko", years: [2025] },
  { name: "Ekyam", slug: "ekyam", years: [2025] },
  { name: "Extend", slug: "extend", years: [2023, 2024, 2025] },
  { name: "Fermàt", slug: "fermat", years: [2025] },
  { name: "Firework", slug: "firework", years: [2024] },
  { name: "Flex", slug: "flex", years: [2024, 2025] },
  { name: "Flexport", slug: "flexport", years: [2025, 2026], current: true },
  { name: "Frate", slug: "frate", years: [2025] },
  { name: "Fulfil", slug: "fulfil", years: [2025] },
  { name: "GoBolt", slug: "gobolt", years: [2023, 2025] },
  { name: "Goody", slug: "goody", years: [2025] },
  { name: "Gorgias", slug: "gorgias", years: [2025, 2026], current: true },
  { name: "Graphite", slug: "graphite", years: [2024] },
  { name: "Haus", slug: "haus", years: [2025, 2026], current: true },
  { name: "Highbeam", slug: "highbeam", years: [2025, 2026], current: true },
  { name: "Horatio", slug: "horatio", years: [2025] },
  { name: "Ikigai", slug: "ikigai", years: [2025] },
  { name: "Kynship", slug: "kynship", years: [2025] },
  { name: "Latham & Watkins", slug: "latham-watkins", years: [2025] },
  { name: "Leftlane", slug: "leftlane", years: [2023] },
  { name: "Loop", slug: "loop", years: [2024] },
  { name: "Maverix", slug: "maverix", years: [2023] },
  { name: "NBCUniversal", slug: "nbcuniversal", years: [2023, 2024, 2025, 2026], current: true },
  { name: "Northbeam", slug: "northbeam", years: [2024, 2025] },
  { name: "Nostra", slug: "nostra", years: [2025, 2026], current: true },
  { name: "Numeral", slug: "numeral", years: [2025, 2026], current: true },
  { name: "Okendo", slug: "okendo", years: [2025] },
  { name: "OpenBorder", slug: "openborder", years: [2023, 2024, 2025] },
  { name: "Ordergroove", slug: "ordergroove", years: [2025, 2026], current: true },
  { name: "Orita", slug: "orita", years: [2025] },
  { name: "P72", slug: "p72", years: [2023] },
  { name: "Parker", slug: "parker", years: [2025] },
  { name: "Passport", slug: "passport", years: [2025, 2026], current: true },
  { name: "Pattern", slug: "pattern", years: [2025] },
  { name: "Pinterest", slug: "pinterest", years: [2025] },
  { name: "Pixis", slug: "pixis", years: [2023, 2024, 2025] },
  { name: "PLTFRM", slug: "pltfrm", years: [2025] },
  { name: "Postscript", slug: "postscript", years: [2023, 2024, 2025] },
  { name: "Pretty Damn Quick", slug: "pretty-damn-quick", years: [2024] },
  { name: "Ratzpack Media", slug: "ratzpack-media", years: [2025] },
  { name: "REDO", slug: "redo", years: [2025] },
  { name: "Rep AI", slug: "rep-ai", years: [2026], current: true },
  { name: "Retention.com", slug: "retention-com", years: [2023, 2024] },
  { name: "Rework", slug: "rework", years: [2025, 2026], current: true },
  { name: "Richpanel", slug: "richpanel", years: [2025, 2026], current: true },
  { name: "Rise.ai", slug: "rise-ai", years: [2024, 2025] },
  { name: "Rivo", slug: "rivo", years: [2025] },
  { name: "Sage", slug: "sage", years: [2025] },
  { name: "SARAL", slug: "saral", years: [2025] },
  { name: "Saras Analytics", slug: "saras-analytics", years: [2025, 2026], current: true },
  { name: "Seair", slug: "seair", years: [2025] },
  { name: "ShipBob", slug: "shipbob", years: [2025] },
  { name: "Shipfusion", slug: "shipfusion", years: [2025] },
  { name: "Shopify", slug: "shopify", years: [2025] },
  { name: "Skio", slug: "skio", years: [2025] },
  { name: "Smartscout", slug: "smartscout", years: [2025] },
  { name: "Snapchat", slug: "snapchat", years: [2025] },
  { name: "Socioh", slug: "socioh", years: [2025] },
  { name: "[solidcore]", slug: "solidcore", years: [2025] },
  { name: "Spartan", slug: "spartan", years: [2025] },
  { name: "Stord", slug: "stord", years: [2025, 2026], current: true },
  { name: "StreetTalk", slug: "streettalk", years: [2025] },
  { name: "Tapcart", slug: "tapcart", years: [2024, 2025] },
  { name: "Tatari", slug: "tatari", years: [2024, 2025] },
  { name: "Tectonic", slug: "tectonic", years: [2025] },
  { name: "TestParty", slug: "testparty", years: [2025] },
  { name: "Tie", slug: "tie", years: [2025] },
  { name: "TikTok Shop", slug: "tiktok-shop", years: [2025] },
  { name: "Treat", slug: "treat", years: [2023] },
  { name: "Triple Whale", slug: "triple-whale", years: [2023] },
  { name: "Universal Ads", slug: "universal-ads", years: [2026], current: true },
  { name: "Videowise", slug: "videowise", years: [2026], current: true },
  { name: "Vibe.co", slug: "vibe-co", years: [2025] },
  { name: "Voyantis", slug: "voyantis", years: [2023] },
  { name: "Within", slug: "within", years: [2025, 2026], current: true },
  { name: "With Coverage", slug: "with-coverage", years: [2025] },
  { name: "Workmagic", slug: "workmagic", years: [2025, 2026], current: true },
  { name: "Yotpo", slug: "yotpo", years: [2025] },
];
